services:
  postgres:
    image: postgres:15-alpine
    container_name: glucoforecast-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: glucoforecast
      POSTGRES_PASSWORD: glucoforecast123
      POSTGRES_DB: glucoforecast
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U glucoforecast -d glucoforecast" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: