-- CREATE TABLE "account" (
-- 	"userId" uuid NOT NULL,
-- 	"type" text NOT NULL,
-- 	"provider" text NOT NULL,
-- 	"providerAccountId" text NOT NULL,
-- 	"refresh_token" text,
-- 	"access_token" text,
-- 	"expires_at" integer,
-- 	"token_type" text,
-- 	"scope" text,
-- 	"id_token" text,
-- 	"session_state" text
-- );
-- --> statement-breakpoint
-- CREATE TABLE "csv_readings" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"user_id" uuid NOT NULL,
-- 	"glucose" numeric(10, 2),
-- 	"timestamp" timestamp with time zone NOT NULL,
-- 	"record_type" varchar(2) NOT NULL,
-- 	"rapid_insulin" numeric(10, 2),
-- 	"long_insulin" numeric(10, 2),
-- 	"carbs" numeric(10, 2),
-- 	"notes" text,
-- 	"device" varchar(255),
-- 	"serial_number" varchar(255)
-- );
-- --> statement-breakpoint
-- CREATE TABLE "sessions" (
-- 	"session_token" text PRIMARY KEY NOT NULL,
-- 	"userId" uuid NOT NULL,
-- 	"expires" timestamp with time zone NOT NULL
-- );
-- --> statement-breakpoint
-- CREATE TABLE "uploaded_files" (
-- 	"id" serial PRIMARY KEY NOT NULL,
-- 	"user_id" uuid NOT NULL,
-- 	"filename" text NOT NULL,
-- 	"original_filename" text NOT NULL,
-- 	"file_size" integer NOT NULL,
-- 	"mime_type" varchar(100),
-- 	"records_processed" integer DEFAULT 0,
-- 	"uploaded_at" timestamp with time zone DEFAULT now()
-- );
-- --> statement-breakpoint
-- CREATE TABLE "users" (
-- 	"id" uuid PRIMARY KEY NOT NULL,
-- 	"name" varchar(255),
-- 	"email" varchar(255) NOT NULL,
-- 	"password" text NOT NULL,
-- 	"created_at" timestamp with time zone DEFAULT now(),
-- 	"email_verified_at" timestamp with time zone DEFAULT now(),
-- 	"image" text,
-- 	CONSTRAINT "users_email_unique" UNIQUE("email")
-- );
-- --> statement-breakpoint
-- CREATE TABLE "verification_token" (
-- 	"identifier" text NOT NULL,
-- 	"token" text NOT NULL,
-- 	"expires" timestamp with time zone NOT NULL
-- );
-- --> statement-breakpoint
-- ALTER TABLE "account" ADD CONSTRAINT "account_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "csv_readings" ADD CONSTRAINT "csv_readings_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "sessions" ADD CONSTRAINT "sessions_userId_users_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- ALTER TABLE "uploaded_files" ADD CONSTRAINT "uploaded_files_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
-- CREATE UNIQUE INDEX "csv_readings_timestamp_type_idx" ON "csv_readings" USING btree ("user_id","timestamp","record_type");